spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration
checkout:
  catalog:
    products:
      - id: APPLE
        name: Apple
        unit-price: "0.30"
      - id: BANANA
        name: Banana
        unit-price: "0.50"
      - id: ORANGE
        name: Orange
        unit-price: "0.80"
    offers:
      - product-id: APPLE
        quantity: 2
        bundle-price: "0.45"
      - product-id: BANANA
        quantity: 3
        bundle-price: "1.20"
